# Generated by Django 3.0.2 on 2020-01-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=8)),
                ('book_name', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('publication', models.CharField(max_length=20)),
                ('book_type', models.CharField(max_length=20)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
    ]
