# Generated by Django 3.0.2 on 2020-01-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_details',
            name='edition',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
